### ISSUE TITLE
Error when choosing featureset

### ISSUE THREAD

**Issue by dsb66** [thomsonlab/popalign#14]
When running the function:

PA.choose_featureset(pop, alpha = 0.1, multiplier=9)

choosing values of multiplier outside of the range 1-8, the function terminates with the error:

/usr/local/bin/miniconda3/envs/popalign/lib/python3.8/site-packages/popalign/popalign.py in find_best_m(pop, alpha, multiplier)
   1382         jrange= range(1,8)
   1383         if multiplier not in jrange:
-> 1384                 jrange.append(multiplier)
   1385                 jrange = np.sort(jrange).tolist()
   1386 
AttributeError: 'range' object has no attribute 'append'

Also, the instructions say that 'multiplier' is a float but the function only works with integer values. Using decimal values returns the same AttributeError.

**Comment by sisichen-dev** [comment]
@dsb66. Thanks for flagging this -- jrange should have been a list and not a range object. By changing the variable this should allow you to add new multiplier values. Also multiplier is an int and not a float and that is now updated in the function comments.
